// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/client/service.proto

#include "api/client/service.pb.h"
#include "api/client/service.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace nighthawk {
namespace client {

class MockNighthawkServiceStub : public NighthawkService::StubInterface {
 public:
  MOCK_METHOD3(QueueRun, ::grpc::Status(::grpc::ClientContext* context, const ::nighthawk::client::CommandLineOptions& request, ::nighthawk::client::Output* response));
  MOCK_METHOD3(AsyncQueueRunRaw, ::grpc::ClientAsyncResponseReaderInterface< ::nighthawk::client::Output>*(::grpc::ClientContext* context, const ::nighthawk::client::CommandLineOptions& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncQueueRunRaw, ::grpc::ClientAsyncResponseReaderInterface< ::nighthawk::client::Output>*(::grpc::ClientContext* context, const ::nighthawk::client::CommandLineOptions& request, ::grpc::CompletionQueue* cq));
};

} // namespace nighthawk
} // namespace client

